# Generated by Django 5.1.4 on 2024-12-11 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ingredientDb',
            fields=[
                ('ingredientId', models.IntegerField(primary_key=True, serialize=False)),
                ('ingredientName', models.CharField(max_length=50)),
                ('userName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='recipeDb',
            fields=[
                ('recipeId', models.IntegerField(primary_key=True, serialize=False)),
                ('recipeName', models.CharField(max_length=200)),
                ('calories', models.IntegerField()),
                ('userName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recepies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
